name: CI Build
on: 
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [master]
jobs:  
  android:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: android-ndk-r21e
        key: ${{ runner.os }}-android-ndk
    - name: Install Dependencies
      run: sudo apt-get install -y swig4.0
    - name: Build
      run: |
        cmake -P ci-build.cmake
        cmake --build build -- -j 2
      env:
        ANDROID: true
    - name: zip SDK
      id: package
      run: |
        [[ $GITHUB_REF = refs/tags/* ]] && VERNAME=${GITHUB_REF##*/} || VERNAME="master"
        echo "ver=${VERNAME}" >> $GITHUB_OUTPUT
        cd build && zip -qr ogre-sdk-android-${VERNAME}-arm64-v8a.zip *
    - name: Upload artifact to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: ogre-sdk-android-${{ steps.package.outputs.ver }}-arm64-v8a.zip
        path: build/OgreJNI/ogre-sdk-android-${{ steps.package.outputs.ver }}-arm64-v8a.zip

      
